language: c++
sudo: required

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      name: "Linux Bionic"
      env:
        - CC=gcc-9
        - CXX=g++-9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libcfitsio-dev
    - os: osx
      osx_image: xcode11.3
      language: shell
      name: "macOS 10.14"
      addons:
        homebrew:
          packages:
            - cmake
            - libomp
            - cfitsio
            - boost
          update: true
    - stage: deploy
      before_install: skip
      install: skip
      script: doxygen docs/Doxyfile
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
      addons:
        apt:
          packages:
            - doxygen

before_install:
    - if [ $TRAVIS_OS_NAME = 'linux' ];
      then pip install --user cpp-coveralls;
      fi
    - mkdir build
    - cd build

install:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make
    - if [ $TRAVIS_OS_NAME = 'osx' ];
      then make install;
      else sudo make install;
      fi

script:
    - make test

after_success:
    - if [ $TRAVIS_OS_NAME = 'linux' ];
      then coveralls --root .. --gcov gcov-9 --exclude build/CMakeFiles --exclude sfof/tests;
      fi
